### ISSUE TITLE
Create Review Guide

### ISSUE THREAD

**Issue by ldecicco-USGS** [ropenscilabs/checkers#2]
Human - review bit!

**Comment by adaish** [comment]
Review Guide - List of Best Practices doc (organised by tier and automation potential) 
[rOpenSciAnalysisGuideunconf2017.docx](https://github.com/ropenscilabs/checkers/files/1032748/rOpenSciAnalysisGuideunconf2017.docx)

**Comment by adaish** [comment]
As a Google Doc for collaboration - https://docs.google.com/document/d/1OYcWJUk-MiM2C1TIHB1Rn6rXoF5fHwRX-7_C12Blx8g/edit#

**Comment by jenniferthompson** [comment]
[Vignette started](https://github.com/ropenscilabs/checkers/blob/master/vignettes/guidelines.Rmd)!

**Comment by jenniferthompson** [comment]
Possibly useful packages to include as suggestions from unconf 2017:
- [skimr](https://github.com/ropenscilabs/skimr) for visualizing raw data
- [packagemetrics](https://github.com/ropenscilabs/packagemetrics) for choosing a "live" package
