### ISSUE TITLE
Identify checks that can be automated

### ISSUE THREAD

**Issue by ldecicco-USGS** [ropenscilabs/checkers#3]

**Comment by adaish** [comment]
# Automatable Checks for checkR
## Data = NA

## Script/Code (organization/structure)
- Using best code practises : setwd(), attach T2
- Library () at beginning of code T3
- Streaming objects in memory (gc) T3
- Platform agnostic T2
- License/ownership T3
- Label chunks


## Package/Organisational

- Long blocks of old/commented code T2
- Version control T2
- README for complex structures T2
- Packages versions 
- Neglected T1
- Know your options T2
Readability 
- Style guidelines T1
- Commenting (%) T1 
- Naming conventions T2
- Adequate white space T3
- Indentation T3

## Analysis Tasks = NA
## Visualisation/Reporting

- Grammar/Spelling T3
- Clear structure and flow T1

List also available here https://docs.google.com/document/d/1OYcWJUk-MiM2C1TIHB1Rn6rXoF5fHwRX-7_C12Blx8g/edit#

**Comment by adaish** [comment]
Tier description
T1 = “Must have” if you don’t have you can’t do anything or can’t trust it. Minimum viable elements.
T2 = “Nice to have” recommended for best practise and important to consider
T3 = “Gold Star” exceptional best practices - great job
