### ISSUE TITLE
Automating checks for proposed inclusion into research-compendium tag?

### ISSUE THREAD

**Issue by cboettig** [ropenscilabs/checkers#33]
@noamross et al, 

@nuest lists the following proposed criteria for a package to be approved for the `research-compendium` tag on Zenodo; these look to me like things we could largely automatically check for from R (could make the review process faster & be an aid to authors).  Would it be worth implementing some/all of these in `checkers`?  

- [ ] The research compendium must be associated with a manuscript or talk slides published with a globally unique identifier (i.e. a DOI). This can be a journal, pre-print platform, file repository, or the manuscript may be included in the compendium directly.

- [ ] If an external document exists, it must be referenced under the "Related identifiers" in the deposit metadata with one of these relations:  "is supplemented by this upload", "is identical to this upload", "has this upload as part", "is part of this upload", "documents this upload", or "is compiled/created by this upload".  [DN: should we leave out the specific relations??]

- [ ] The author(s) of the research compendium should have an ORCID identifier. 

- [ ] The research compendium must include data and code of a scientific analysis.

- [ ] The research compendium must include documentation on how to reproduce the work or includes a literate programming document (R Markdown file, Jupyter Notebook).

- [ ] The research compendium must have one of the "Open" access rights licenses in the Zenodo metadata; it should state licensing information seperately for the parts of the compendium (code, data, text) and easy to find (e.g. in a file "LICENSE", in a README, or in the deposit description).

**Comment by noamross** [comment]
I like this list, but I admit that **checkers** probably needs a "paused"/"abandoned"/"experiment" status badge because the team hasn't been able to pick it up since its original creation. 

In a broader sense, though, you could implement these in **checkers** for R code, but it seems like something that would be more general than that - it seems that the first 1,2,3, and 6 would be directly checked against the Zenodo metadata (or a codemeta.json file), and the other two need to be checked manually for someone to establish that the code does produce the output.

**Comment by njtierney** [comment]
The list sounds great! :)

I agree with @noamross 's points, step 4 and 5 would require human checking, but I think that they could be partially machine checked, perhaps:

Step 4 could have a search for a standard data format (perhaps .csv, for transportability?), but also flag for a human check, and then provide a checklist?

Step 5 could search for an .Rmd or Ipython extension, but again, would require a human check to ensure that it actually reproduces the work.

I would be keen to help jump start checkers to help with getting this project running again, if we want to discuss a reboot / bringing the team back together?

**Comment by nuest** [comment]
The Zenodo curation process is just one person, and I've been wondering how to support that with a GitHub repo or a bot. Having these checks in `checkers` would be very helpful!

Would it be in scope for `checkers` to run tests against the Zenodo API?

**Comment by noamross** [comment]
I'm glad there's interest in getting the band back together, @njtierney!  I will admit that its unlikely that I can drive much of this at the moment as I'm a bit too swamped. 

I'm unsure whether `checkers` is the right vehicle for this work, @nuest.  Its paradigm is to run checks locally on a folder of files, while I think the bulk of the job you are describing is querying the API, flagging areas for the human reviewer to check manually, setting up the bot and hooks to support this.  It's not out-of-scope but those tasks are all pretty independent of the package's codebase.

**Comment by cboettig** [comment]
@noamross good points.  Guess this leaves open the question of whether it would be more expedient / strategic to develop a curation assistant separately or take this as an opportunity to reboot some of `checkers` as well (and maybe draw in input from the 27 folks already watching `checkers` rather than start again again?)  

Re automation, I tend to have a more minimal / optimistic intuition about automating.  I don't see the Zenodo API being needed for this provided we're checking R-package-style compendia (though I see that the `research-compendium` tag would apply to other cases as well).  If we assume researcher is using the Zenodo-GitHub integration, the DOI comes for automatically (1), along with a relatedIdentifier link back to the GitHub URL (2).  ORCID could/should be in the R DESCRIPTION file (3), as would known licenses (6).  I'd look for common extensions for code (*.Rmd, *.R) and data (a longer list of extensions? a data file?  admit this last one could be tricky-- some data may be too large for a compendium or may be already published data that is accessed by link, not shipped in the compendium -- that's a use case we should puzzle over).  But I think getting a green light on auto-detection of these 6 or 7 things, even if verified later, would definitely facilitate the curation process.

**Comment by noamross** [comment]
I think if **checkers** aims to have a check that "this folder is a valid
R-style Zenodo research compendium," it would straightforward to write the
checks, which would basically require inspecting a zenodo.json or
codemeta.json file locally and reporting on some file types found. But this
requires that the curator download it to run checkers locally - if one aims
to be general

That said, these are checks it would make sense to write, which could be
bundled into a "compendium" list of checks
- Has a DESCRIPTION file
- Has author ORCiD id in the DESCRIPTION
- Has an appropriate license
- Has a codemeta or zenodo file that matches description


I'd also include in this bundle of checks
- Is version controlled
- Version control is clean (no uncommitted changes/files)
- All packages called in code are listed in DESCRIPTION
- Includes a README

Of course, we could try to be a little more strict in enforcing what an
R-style compendium is, with things like:
- Global R function definitions are under an R/ directory
- Uses a build system if contains >1 non-functional defining script or
literate code document
-...

I note that data could also be in a package, or one could have a data-free
theoretical compendium, too.

(These wouldn't be part of the Zenodo check, I think, just spitballling a
bit here :))
