### ISSUE TITLE
Check: Is folder under version control?

### ISSUE THREAD

**Issue by noamross** [ropenscilabs/checkers#5]
Check whether the folder has a `.git` or `.svn` file
Prep: list project files

**Comment by nistara** [comment]
Fixed via pull request #13

**Comment by jsta** [comment]
This check flags sub-folders that are under version control but are tracked in a parent folder.

**Comment by noamross** [comment]
Do you mean it finds subfolders that are tracked, but doesn't check the top level, so gives a false negative?

(I should note that this is mostly in pause mode awaiting carving time out to continue to work on it, but appreciate the feedback! Are you using this actively?)

**Comment by jsta** [comment]
* Yes. I think it is common to have a top level folder holding `.git` and a sub-folder with scripts.

* Mostly exploring at this point. I will say I wish that line length checking was not in the default yaml. It is an overwhelming number of flags when run on a large project.
